@extends('admin.master.master')
@section('title','Inventory Purchases')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Purchases / Received Supply</h1><p class="text-muted mb-0">Actual supplier invoices and stock receipts created from approved Purchase Vouchers.</p></div>@can('inventory-purchase-voucher-manage')<a href="{{ route('inventory.purchase-vouchers.create') }}" class="progga-btn progga-btn-primary"><i class="bi bi-plus-lg"></i> New Purchase Voucher</a>@endcan</div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="progga-card mb-4 inventory-filter-card"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-md-4"><label class="progga-form-label">Vendor</label><select name="vendor_id" class="progga-form-control"><option value="">All vendors</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}" @selected((string)request('vendor_id')===(string)$vendor->id)>{{ $vendor->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="progga-form-label">Status</label><select name="status" class="progga-form-control"><option value="">All status</option><option value="DRAFT" @selected(request('status')==='DRAFT')>Draft</option><option value="RECEIVED" @selected(request('status')==='RECEIVED')>Received</option></select></div><div class="col-md-auto"><button class="progga-btn progga-btn-secondary">Apply Filter</button></div><div class="col-md-auto"><a href="{{ route('inventory.purchases.index') }}" class="progga-btn progga-btn-light">Clear</a></div></form></div></div>
    <div class="progga-card">
        <div class="progga-card-header inventory-list-toolbar"><div class="inventory-result-copy"><span class="fw-semibold">Purchase List</span><small class="text-muted" id="inventoryResultCount">{{ $purchases->total() }} {{ $purchases->total() === 1 ? 'record' : 'records' }}</small></div><div class="inventory-search-wrap"><i class="bi bi-search inventory-search-icon"></i><input type="search" id="inventorySearch" class="progga-form-control inventory-search-input" value="{{ request('search') }}" placeholder="Search purchase, voucher, invoice or reference..." autocomplete="off"><button type="button" id="inventorySearchClear" class="inventory-search-clear"><i class="bi bi-x-lg"></i></button></div></div>
        <div id="inventoryListContent"><div class="progga-table-wrapper" style="border:none;border-radius:0;"><table class="progga-table"><thead><tr><th style="width:70px;">SL</th><th>Purchase / Voucher</th><th>Vendor</th><th>Date</th><th>Items</th><th>Total</th><th>Paid / Due</th><th>Status / GRN</th><th style="width:130px;">Actions</th></tr></thead><tbody>
        @forelse($purchases as $purchase)<tr><td>{{ ($purchases->firstItem() ?? 1)+$loop->index }}</td><td><a href="{{ route('inventory.purchases.show',$purchase) }}"><strong>{{ $purchase->purchase_no }}</strong></a><br><small class="text-muted">Invoice: {{ $purchase->invoice_no ?: '—' }}</small>@if($purchase->voucher)<br><small><a href="{{ route('inventory.purchase-vouchers.show',$purchase->voucher) }}">Voucher: {{ $purchase->voucher->voucher_no }}</a></small>@endif</td><td>{{ $purchase->vendor?->name }}</td><td>{{ optional($purchase->purchase_date)->format('d M Y') }}</td><td>{{ $purchase->items_count }}</td><td><strong>৳{{ number_format((float)$purchase->total,2) }}</strong></td><td><span class="text-success">Paid: ৳{{ number_format($purchase->paidAmount(),2) }}</span><br><span class="{{ $purchase->dueAmount()>0 ? 'text-danger' : 'text-muted' }}">Due: ৳{{ number_format($purchase->dueAmount(),2) }}</span></td><td><span class="progga-badge progga-badge-{{ $purchase->status==='RECEIVED'?'success':'warning' }}">{{ $purchase->status }}</span><br><small class="text-muted">GRN: {{ $purchase->grn_status ?: 'PENDING' }}</small></td><td><div class="progga-table-actions"><a href="{{ route('inventory.purchases.show',$purchase) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="View"><i class="bi bi-eye"></i></a><a href="{{ route('inventory.purchases.invoice-pdf',$purchase) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Download Purchase Invoice PDF"><i class="bi bi-file-earmark-pdf"></i></a>@if($purchase->isEditable()) @can('inventory-purchase-create')<a href="{{ route('inventory.purchases.edit',$purchase) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Edit"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('inventory.purchases.destroy',$purchase) }}" class="d-inline">@csrf @method('DELETE')<button type="button" class="progga-btn progga-btn-danger progga-btn-icon progga-btn-sm" title="Delete" data-delete-name="{{ $purchase->purchase_no }}" onclick="inventoryConfirmDelete(this)"><i class="bi bi-trash"></i></button></form>@endcan @endif</div></td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-5">No purchases found.</td></tr>@endforelse
        </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$purchases,'label'=>'purchases'])</div>
    </div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.purchases.index')])
@endsection
