@extends('admin.master.master')
@section('title','Salary Advance — '.$restaurantSettingName)
@section('css') @include('admin.hr.shared.styles') @endsection
@section('body')
<main class="progga-content"><div class="hr-shell">
<div class="progga-page-header"><div><h1 class="progga-page-title">Salary Advance</h1><div class="progga-breadcrumb"><a href="{{ route('hr.dashboard') }}" class="progga-breadcrumb-item">HR Dashboard</a><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item active">Salary Advance</span></div></div>
@can('salary-advance-create')<button class="progga-btn progga-btn-primary" id="advanceAddBtn"><i class="bi bi-plus-lg"></i> Add Advance</button>@endcan</div>
<div class="hr-stat-grid"><div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-cash-coin"></i></div><div><div class="hr-stat-value">{{ $activeCount }}</div><div class="hr-stat-label">Active Advances</div></div></div><div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-wallet2"></i></div><div><div class="hr-stat-value">৳{{ number_format((float)$totalIssued,2) }}</div><div class="hr-stat-label">Total Issued</div></div></div><div class="hr-stat-card"><div class="hr-stat-icon"><i class="bi bi-arrow-return-left"></i></div><div><div class="hr-stat-value">৳{{ number_format((float)$totalRecovered,2) }}</div><div class="hr-stat-label">Recovered</div></div></div></div>
<div class="hr-card mb-3"><div class="hr-card-body"><div class="row g-2 align-items-center"><div class="col-lg-4"><select id="advanceEmployeeFilter" class="hr-select2"><option value="">All Employees</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_code }} — {{ $e->name }}</option>@endforeach</select></div><div class="col-lg-3"><select id="advanceStatus" class="hr-select2" data-search="false"><option value="">All Status</option><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div class="col-lg-2"><button id="advanceReset" class="progga-btn progga-btn-outline w-100"><i class="bi bi-arrow-counterclockwise"></i> Reset</button></div><div class="col-lg-3"><div class="hr-search"><i class="bi bi-search"></i><input id="advanceSearch" class="progga-form-control" placeholder="Type or paste to search"></div></div></div></div></div>
<div class="hr-card" id="advanceTable"><div class="hr-empty py-5"><div class="spinner-border spinner-border-sm"></div><div class="mt-2">Loading...</div></div></div>
</div></main>
<div class="modal fade progga-modal" id="advanceModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Salary Advance</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="advanceForm">@csrf<input type="hidden" name="id"><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="progga-form-label">Employee *</label><select name="employee_id" class="progga-select advance-select" required><option value="">Select Employee</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->employee_code }} — {{ $e->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="progga-form-label">Advance Date *</label><input type="date" name="advance_date" class="progga-form-control" value="{{ now()->toDateString() }}" required></div><div class="col-md-3"><label class="progga-form-label">Amount *</label><input type="number" step="0.01" min="0.01" name="amount" class="progga-form-control" required></div><div class="col-md-6"><label class="progga-form-label">Recovery Start Month *</label><input type="month" id="advanceRecoveryMonth" class="progga-form-control" value="{{ now()->format('Y-m') }}" required><input type="hidden" name="recovery_start_month"></div><div class="col-md-6"><label class="progga-form-label">Monthly Recovery / Installment</label><input type="number" step="0.01" min="0.01" name="installment_amount" class="progga-form-control"><div class="hr-muted mt-1">Leave blank to recover the full remaining balance in the first payroll month.</div></div><div class="col-12"><label class="progga-form-label">Notes</label><textarea name="notes" class="progga-form-control" rows="2"></textarea></div></div></div><div class="modal-footer"><button type="button" class="progga-btn progga-btn-outline" data-bs-dismiss="modal">Cancel</button><button class="progga-btn progga-btn-primary" type="submit">Save Advance</button></div></form></div></div></div>
<div class="modal fade progga-modal" id="advanceRepayModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Record Advance Repayment</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form id="advanceRepayForm">@csrf<input type="hidden" name="id"><div class="modal-body"><div class="mb-3"><label class="progga-form-label">Outstanding</label><input id="advanceOutstanding" class="progga-form-control" disabled></div><div class="mb-3"><label class="progga-form-label">Payment Date *</label><input type="date" name="payment_date" class="progga-form-control" value="{{ now()->toDateString() }}" required></div><div class="mb-3"><label class="progga-form-label">Amount *</label><input type="number" step="0.01" min="0.01" name="amount" class="progga-form-control" required></div><div class="mb-3"><label class="progga-form-label">Reference</label><input name="reference_number" class="progga-form-control"></div><div><label class="progga-form-label">Notes</label><textarea name="notes" class="progga-form-control" rows="2"></textarea></div></div><div class="modal-footer"><button class="progga-btn progga-btn-outline" type="button" data-bs-dismiss="modal">Cancel</button><button class="progga-btn progga-btn-primary" type="submit">Record Repayment</button></div></form></div></div></div>
@endsection
@section('script') @include('admin.hr.shared.plugins')
<script>
$(function(){let page=1,timer; HrUi.initSelect2('.hr-select2'); HrUi.initSelect2('.advance-select');
function load(p=1){page=p;$('#advanceTable').addClass('hr-table-loading');$.get(@json(route('hr.salary-advances.index')),{page,search:$('#advanceSearch').val(),employee_id:HrUi.selectValue('advanceEmployeeFilter'),status:HrUi.selectValue('advanceStatus')}).done(h=>$('#advanceTable').html(h)).fail(x=>Swal.fire('Error',x.responseJSON?.message||'Failed to load salary advances.','error')).always(()=>$('#advanceTable').removeClass('hr-table-loading'));}
$('#advanceSearch').on('input',()=>{clearTimeout(timer);timer=setTimeout(()=>load(1),300)}); $('.hr-select2').on('change',()=>load(1)); $('#advanceReset').on('click',()=>{$('#advanceSearch').val('');HrUi.resetSelect('advanceEmployeeFilter');HrUi.resetSelect('advanceStatus');load(1)}); $(document).on('click','#advanceTable .report-page-link:not(.disabled)',function(e){e.preventDefault();load(new URL(this.href).searchParams.get('page')||1)});
function monthDate(){const m=$('#advanceRecoveryMonth').val();$('#advanceForm [name="recovery_start_month"]').val(m?m+'-01':'')}
$('#advanceAddBtn').on('click',()=>{$('#advanceForm')[0].reset();$('#advanceForm [name=id]').val('');$('#advanceRecoveryMonth').val(@json(now()->format('Y-m')));monthDate();$('#advanceModal').modal('show')});
$(document).on('click','.advance-edit',function(){const r=JSON.parse(this.dataset.record);$('#advanceForm [name=id]').val(r.id);$('.advance-select').val(r.employee_id).trigger('change');$('#advanceForm [name=advance_date]').val(String(r.advance_date).substring(0,10));$('#advanceForm [name=amount]').val(r.amount);$('#advanceRecoveryMonth').val(String(r.recovery_start_month).substring(0,7));$('#advanceForm [name=installment_amount]').val(r.installment_amount||'');$('#advanceForm [name=notes]').val(r.notes||'');monthDate();$('#advanceModal').modal('show')});
$('#advanceForm').on('submit',function(e){e.preventDefault();monthDate();const id=$(this).find('[name=id]').val();$.ajax({url:id?@json(url('/hr/salary-advances'))+'/'+id:@json(route('hr.salary-advances.store')),type:id?'PUT':'POST',data:$(this).serialize()}).done(r=>{$('#advanceModal').modal('hide');Swal.fire({icon:'success',title:'Saved',text:r.message,timer:1300,showConfirmButton:false});load(page)}).fail(x=>Swal.fire('Error',x.responseJSON?.message||Object.values(x.responseJSON?.errors||{})[0]?.[0]||'Could not save.','error'))});
$(document).on('click','.advance-repay',function(){$('#advanceRepayForm')[0].reset();$('#advanceRepayForm [name=id]').val(this.dataset.id);$('#advanceOutstanding').val('৳'+this.dataset.outstanding);$('#advanceRepayForm [name=payment_date]').val(@json(now()->toDateString()));$('#advanceRepayModal').modal('show')});
$('#advanceRepayForm').on('submit',function(e){e.preventDefault();const id=$(this).find('[name=id]').val();$.post(@json(url('/hr/salary-advances'))+'/'+id+'/repay',$(this).serialize()).done(r=>{$('#advanceRepayModal').modal('hide');Swal.fire({icon:'success',title:'Recorded',text:r.message,timer:1300,showConfirmButton:false});load(page)}).fail(x=>Swal.fire('Error',x.responseJSON?.message||'Could not record repayment.','error'))});
$(document).on('click','.advance-delete',function(){const id=this.dataset.id;Swal.fire({title:'Delete salary advance?',icon:'warning',showCancelButton:true,confirmButtonText:'Delete',confirmButtonColor:'#c63d3d'}).then(r=>{if(!r.isConfirmed)return;$.ajax({url:@json(url('/hr/salary-advances'))+'/'+id,type:'DELETE',data:{_token:@json(csrf_token())}}).done(x=>{Swal.fire({icon:'success',title:'Deleted',text:x.message,timer:1200,showConfirmButton:false});load(page)}).fail(x=>Swal.fire('Error',x.responseJSON?.message||'Could not delete.','error'))})}); load();});
</script>@endsection
