@extends('admin.master.master')
@section('title','TIPSOI Device Assignment — '.$restaurantSettingName)
@section('css')@include('admin.hr.shared.styles')@endsection
@section('body')
<main class="progga-content"><div class="hr-shell"><div class="progga-page-header"><div><h1 class="progga-page-title">TIPSOI Device Assignment</h1><div class="progga-breadcrumb"><a href="{{ route('home') }}" class="progga-breadcrumb-item">Dashboard</a><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">HR</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">TIPSOI</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item active">Device Assignment</span></div></div><a href="{{ route('hr.tipsoi.devices.index') }}" class="progga-btn progga-btn-outline">Device List</a></div>
@if(!$attendanceSetting?->tipsoi_enabled)<div class="alert alert-warning">TIPSOI is disabled in HR Settings.</div>@endif
<div class="row g-3"><div class="col-lg-6"><div class="hr-card h-100"><div class="hr-card-header"><div><div class="hr-card-title">Single Allocate / Revoke</div><div class="hr-card-subtitle">Assign one employee to one device or revoke that assignment.</div></div></div><div class="hr-card-body"><form action="{{ route('hr.tipsoi.allocations.store') }}" method="POST">@csrf<div class="mb-3"><label class="progga-form-label">Employee</label><select name="employee_id" class="progga-select" required><option value="">Select employee</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->name }} ({{ $e->employee_code }})</option>@endforeach</select></div><div class="mb-3"><label class="progga-form-label">Device</label><select name="device_identifier" class="progga-select" required><option value="">Select device</option>@foreach($devices as $d)<option value="{{ $d->identifier }}">{{ $d->identifier }}{{ $d->location ? ' · '.$d->location : '' }}</option>@endforeach</select></div><div class="mb-3"><label class="progga-form-label">Action</label><select name="action" class="progga-select"><option value="allocate">Allocate</option><option value="revoke">Revoke</option></select></div><button class="progga-btn progga-btn-primary">Send Request</button></form></div></div></div>
<div class="col-lg-6"><div class="hr-card h-100"><div class="hr-card-header"><div><div class="hr-card-title">Batch Allocate / Revoke</div><div class="hr-card-subtitle">Assign or revoke multiple employees across multiple devices.</div></div></div><div class="hr-card-body"><form action="{{ route('hr.tipsoi.allocations.batch') }}" method="POST">@csrf<div class="mb-3"><label class="progga-form-label">Employees</label><select name="employee_ids[]" class="progga-select" multiple size="8" required>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->name }} ({{ $e->employee_code }})</option>@endforeach</select></div><div class="mb-3"><label class="progga-form-label">Devices</label><select name="device_identifiers[]" class="progga-select" multiple size="6" required>@foreach($devices as $d)<option value="{{ $d->identifier }}">{{ $d->identifier }}{{ $d->location ? ' · '.$d->location : '' }}</option>@endforeach</select></div><div class="mb-3"><label class="progga-form-label">Action</label><select name="action" class="progga-select"><option value="allocate">Allocate Selected</option><option value="revoke">Revoke Selected</option></select></div><button class="progga-btn progga-btn-primary">Send Batch Request</button></form></div></div></div></div>
</div></main>
@endsection
@section('script')@include('admin.hr.shared.plugins')@endsection
