@extends('admin.master.master')
@section('title','TIPSOI Fingerprint Enrollment — '.$restaurantSettingName)
@section('css')@include('admin.hr.shared.styles')@endsection
@section('body')
<main class="progga-content"><div class="hr-shell">
<div class="progga-page-header"><div><h1 class="progga-page-title">TIPSOI Fingerprint Enrollment</h1><div class="progga-breadcrumb"><a href="{{ route('home') }}" class="progga-breadcrumb-item">Dashboard</a><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">HR</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">TIPSOI</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item active">Fingerprint Enrollment</span></div></div><a href="{{ route('hr.tipsoi.devices.index') }}" class="progga-btn progga-btn-outline"><i class="bi bi-hdd-network"></i> Device List</a></div>
@if(!$attendanceSetting?->tipsoi_enabled)<div class="alert alert-warning">TIPSOI is disabled in HR Settings.</div>@endif
@if($devices->isEmpty())<div class="alert alert-info">No cached device found. Refresh Device List first.</div>@endif
<div class="row g-3">
<div class="col-lg-8"><div class="hr-card"><div class="hr-card-header"><div><div class="hr-card-title">Start Enrollment</div><div class="hr-card-subtitle">Choose employee, device, hand and finger. Employee will be synced first when required.</div></div></div><div class="hr-card-body"><form action="{{ route('hr.tipsoi.fingerprint.start') }}" method="POST" id="fpStartForm">@csrf<div class="row g-3"><div class="col-md-6"><label class="progga-form-label">Employee</label><select name="employee_id" id="fpEmployee" class="progga-select" required><option value="">Select employee</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->name }} ({{ $e->employee_code }}){{ $e->tipsoi_identifier ? ' · Synced' : '' }}</option>@endforeach</select></div><div class="col-md-6"><label class="progga-form-label">Device</label><select name="device_identifier" id="fpDevice" class="progga-select" required><option value="">Select device</option>@foreach($devices as $d)<option value="{{ $d->identifier }}">{{ $d->identifier }}{{ $d->location ? ' · '.$d->location : '' }}</option>@endforeach</select></div><div class="col-md-6"><label class="progga-form-label">Hand</label><select name="hand" class="progga-select"><option value="left">Left</option><option value="right">Right</option></select></div><div class="col-md-6"><label class="progga-form-label">Finger</label><select name="finger" class="progga-select">@foreach(['thumb','index','middle','ring','pinky'] as $f)<option value="{{ $f }}" @selected($f==='index')>{{ ucfirst($f) }}</option>@endforeach</select></div></div><div class="d-flex gap-2 mt-3 flex-wrap"><button class="progga-btn progga-btn-primary"><i class="bi bi-play-fill"></i> Start Enrollment</button><button type="button" id="fpCheckStatus" class="progga-btn progga-btn-outline"><i class="bi bi-activity"></i> Check Status</button></div></form></div></div></div>
<div class="col-lg-4"><div class="hr-card"><div class="hr-card-header"><div class="hr-card-title">Stop Enrollment</div></div><div class="hr-card-body"><form action="{{ route('hr.tipsoi.fingerprint.stop') }}" method="POST">@csrf<label class="progga-form-label">Device</label><select name="device_identifier" class="progga-select mb-3" required><option value="">Select device</option>@foreach($devices as $d)<option value="{{ $d->identifier }}">{{ $d->identifier }}{{ $d->location ? ' · '.$d->location : '' }}</option>@endforeach</select><button class="progga-btn progga-btn-outline w-100 justify-content-center"><i class="bi bi-stop-fill"></i> Stop Enrollment</button></form><hr><div id="fpStatusBox" class="small text-muted">Status has not been checked.</div></div></div></div>
</div></div></main>
@endsection
@section('script')@include('admin.hr.shared.plugins')<script>$(function(){$('#fpCheckStatus').on('click',function(){const employee=$('#fpEmployee').val(),device=$('#fpDevice').val();if(!employee||!device){Swal.fire('Select employee and device','','warning');return;}const b=$(this).prop('disabled',true);$.get("{{ route('hr.tipsoi.fingerprint.status') }}",{employee_id:employee,device_identifier:device}).done(function(r){const d=r.data||{};$('#fpStatusBox').html('<strong>Running:</strong> '+(d.running?'Yes':'No')+'<br><strong>Status:</strong> '+(d.status?'Complete':'Pending / Not Running')+'<br><strong>Person:</strong> '+(d.name||'-')+'<br><strong>From:</strong> '+(d.from||'-')+'<br><strong>To:</strong> '+(d.to||'-'));}).fail(function(x){Swal.fire('Status check failed',x.responseJSON?.message||'Failed','error');}).always(function(){b.prop('disabled',false);});});});</script>@endsection
