@extends('admin.master.master')
@section('title','TIPSOI Raw Punch Logs — '.$restaurantSettingName)
@section('css')@include('admin.hr.shared.styles')@endsection
@section('body')
<main class="progga-content"><div class="hr-shell"><div class="progga-page-header"><div><h1 class="progga-page-title">TIPSOI Raw Punch Logs</h1><div class="progga-breadcrumb"><a href="{{ route('home') }}" class="progga-breadcrumb-item">Dashboard</a><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">HR</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item">TIPSOI</span><span class="progga-breadcrumb-sep">/</span><span class="progga-breadcrumb-item active">Raw Punch Logs</span></div></div><a href="{{ route('hr.attendance.index') }}" class="progga-btn progga-btn-outline">Attendance Sync</a></div>
<div class="hr-card mb-3"><div class="hr-card-header"><div><div class="hr-card-title">Fetch Raw Punches</div><div class="hr-card-subtitle">Pull device punches for a date range and save them locally for audit.</div></div></div><div class="hr-card-body"><form method="POST" action="{{ route('hr.tipsoi.raw-logs.refresh') }}" class="row g-2 align-items-end">@csrf<div class="col-md-4"><label class="progga-form-label">From Date</label><input type="date" name="from_date" class="progga-form-control" value="{{ request('from_date',now()->toDateString()) }}" required></div><div class="col-md-4"><label class="progga-form-label">To Date</label><input type="date" name="to_date" class="progga-form-control" value="{{ request('to_date',now()->toDateString()) }}" required></div><div class="col-md-4"><button class="progga-btn progga-btn-primary w-100 justify-content-center"><i class="bi bi-cloud-arrow-down"></i> Fetch Raw Logs</button></div></form></div></div>
<div class="hr-card"><div class="hr-card-body border-bottom"><form method="GET" action="{{ route('hr.tipsoi.raw-logs.index') }}" class="row g-2 align-items-end"><div class="col-md-2"><label class="progga-form-label">From</label><input type="date" name="from_date" class="progga-form-control" value="{{ request('from_date') }}"></div><div class="col-md-2"><label class="progga-form-label">To</label><input type="date" name="to_date" class="progga-form-control" value="{{ request('to_date') }}"></div><div class="col-md-2"><label class="progga-form-label">Method</label><select name="type" class="progga-select"><option value="">All</option>@foreach(['card','fingerprint','face'] as $t)<option value="{{ $t }}" @selected(request('type')===$t)>{{ ucfirst($t) }}</option>@endforeach</select></div><div class="col-md-4"><label class="progga-form-label">Search</label><input type="text" name="search" class="progga-form-control" value="{{ request('search') }}" placeholder="Employee, identifier, device, RFID"></div><div class="col-md-2"><button class="progga-btn progga-btn-outline w-100 justify-content-center">Filter</button></div></form></div>@include('admin.hr.tipsoi.raw-logs-table',['logs'=>$logs])</div>
</div></main>
@endsection
@section('script')@include('admin.hr.shared.plugins')@endsection
