@extends('admin.master.master')
@section('title','Purchase Vouchers')
@section('body')
<main class="progga-content">
    <div class="progga-page-header"><div><h1 class="progga-page-title">Purchase Vouchers</h1><p class="text-muted mb-0">Approval-first purchasing: Voucher → Officer Approval → Vendor → Supply Receive → Purchase.</p></div>@can('inventory-purchase-voucher-manage')<a href="{{ route('inventory.purchase-vouchers.create') }}" class="progga-btn progga-btn-primary"><i class="bi bi-plus-lg"></i> New Purchase Voucher</a>@endcan</div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="progga-card mb-4"><div class="p-3"><form id="inventoryFilterForm" class="row g-2 align-items-end"><div class="col-md-3"><label class="progga-form-label">Search</label><input type="search" id="inventorySearch" name="search" value="{{ request('search') }}" class="progga-form-control" placeholder="Voucher no / vendor"></div><div class="col-md-3"><label class="progga-form-label">Vendor</label><select name="vendor_id" class="progga-form-control"><option value="">All vendors</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}" @selected((string)request('vendor_id')===(string)$vendor->id)>{{ $vendor->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="progga-form-label">Status</label><select name="status" class="progga-form-control"><option value="">All status</option>@foreach(['DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','SENT_TO_VENDOR','COMPLETED'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str_replace('_',' ',$status) }}</option>@endforeach</select></div><div class="col-md-auto"><button class="progga-btn progga-btn-secondary">Apply</button></div><div class="col-md-auto"><a href="{{ route('inventory.purchase-vouchers.index') }}" class="progga-btn progga-btn-light">Clear</a></div></form></div></div>
    <div class="progga-card"><div class="progga-card-header"><strong>Voucher List</strong><span class="text-muted small" id="inventoryResultCount">{{ $vouchers->total() }} {{ $vouchers->total()===1?'record':'records' }}</span></div><div id="inventoryListContent"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Voucher</th><th>Vendor</th><th>Date</th><th>Revision</th><th>Items</th><th>Total</th><th>Status</th><th style="width:150px">Actions</th></tr></thead><tbody>
        @forelse($vouchers as $voucher)
        @php $badge = match($voucher->status){'APPROVED','COMPLETED'=>'success','REJECTED'=>'danger','SENT_TO_VENDOR'=>'primary','PENDING_APPROVAL'=>'warning',default=>'secondary'}; @endphp
        <tr><td><a href="{{ route('inventory.purchase-vouchers.show',$voucher) }}"><strong>{{ $voucher->voucher_no }}</strong></a></td><td>{{ $voucher->vendor?->name }}</td><td>{{ optional($voucher->voucher_date)->format('d M Y') }}</td><td>R{{ $voucher->revision_no }}</td><td>{{ $voucher->items_count }}</td><td><strong>৳{{ number_format((float)$voucher->total,2) }}</strong></td><td><span class="badge bg-{{ $badge }} {{ $badge==='warning'?'text-dark':'' }}">{{ str_replace('_',' ',$voucher->status) }}</span></td><td><div class="progga-table-actions"><a href="{{ route('inventory.purchase-vouchers.show',$voucher) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="View"><i class="bi bi-eye"></i></a><a href="{{ route('inventory.purchase-vouchers.approval-history',$voucher) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Approval History / Exchange"><i class="bi bi-arrow-left-right"></i></a><a href="{{ route('inventory.purchase-vouchers.pdf',$voucher) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Voucher PDF"><i class="bi bi-file-earmark-pdf"></i></a>@if($voucher->isEditable())<a href="{{ route('inventory.purchase-vouchers.edit',$voucher) }}" class="progga-btn progga-btn-outline progga-btn-icon progga-btn-sm" title="Edit"><i class="bi bi-pencil"></i></a>@endif</div></td></tr>
        @empty<tr><td colspan="8" class="text-center text-muted py-5">No purchase vouchers found.</td></tr>@endforelse
    </tbody></table></div>@include('admin.inventory.partials.pagination',['paginator'=>$vouchers,'label'=>'vouchers'])</div></div>
</main>
@endsection
@section('script')
@include('admin.inventory.partials.list_assets',['indexUrl'=>route('inventory.purchase-vouchers.index')])
@endsection
