<!doctype html><html><head><meta charset="utf-8"><style>
body{font-family:freesans,sans-serif;font-size:11px;color:#222}.header{text-align:center;margin-bottom:16px}.title{font-size:21px;font-weight:bold}.muted{color:#666}.grid{width:100%;border-collapse:collapse;margin:12px 0}.grid th,.grid td{border:1px solid #bbb;padding:7px}.grid th{background:#f0f2f5;text-align:left}.right{text-align:right}.summary{width:42%;margin-left:auto;border-collapse:collapse}.summary td{padding:5px;border-bottom:1px solid #ddd}.approval{margin-top:20px}.status{font-weight:bold}.small{font-size:9px}.box{border:1px solid #bbb;padding:8px;margin:8px 0}
</style></head><body>
<div class="header"><div class="title">{{ $restaurant?->name ?? config('app.name') }}</div><div>{{ in_array($voucher->status,[\App\Models\PurchaseVoucher::STATUS_APPROVED,\App\Models\PurchaseVoucher::STATUS_SENT_TO_VENDOR,\App\Models\PurchaseVoucher::STATUS_COMPLETED],true) ? 'APPROVED PURCHASE VOUCHER' : 'PURCHASE VOUCHER / PURCHASE REQUISITION' }}</div><div class="muted">{{ $voucher->voucher_no }} · Revision {{ $voucher->revision_no }}</div></div>
<table width="100%"><tr><td><strong>Vendor:</strong> {{ $voucher->vendor?->name }}<br><span class="small">{{ $voucher->vendor?->phone }} {{ $voucher->vendor?->email ? ' · '.$voucher->vendor?->email : '' }}</span></td><td class="right"><strong>Date:</strong> {{ optional($voucher->voucher_date)->format('d M Y') }}<br><strong>Status:</strong> {{ str_replace('_',' ',$voucher->status) }}</td></tr></table>
@if($voucher->reapproval_reason)<div class="box"><strong>Re-approval:</strong> {{ $voucher->reapproval_reason }}</div>@endif
<table class="grid"><thead><tr><th>#</th><th>Ingredient</th><th class="right">Qty</th><th>Unit</th><th class="right">Price</th><th class="right">Total</th></tr></thead><tbody>@foreach($voucher->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->ingredient?->name }}</td><td class="right">{{ rtrim(rtrim((string)$item->quantity,'0'),'.') }}</td><td>{{ $item->packageConversion?->label ?: ($item->unit?->name.' '.$item->unit?->symbol) }}</td><td class="right">৳{{ number_format((float)$item->unit_price,2) }}</td><td class="right">৳{{ number_format((float)$item->line_total,2) }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>Subtotal</td><td class="right">৳{{ number_format((float)$voucher->subtotal,2) }}</td></tr><tr><td>Discount</td><td class="right">৳{{ number_format((float)$voucher->discount,2) }}</td></tr><tr><td>Tax</td><td class="right">৳{{ number_format((float)$voucher->tax,2) }}</td></tr><tr><td><strong>Total</strong></td><td class="right"><strong>৳{{ number_format((float)$voucher->total,2) }}</strong></td></tr></table>
@if($voucher->notes)<div class="box"><strong>Notes:</strong> {{ $voucher->notes }}</div>@endif
<div class="approval"><h3>Approval Exchange Record</h3><table class="grid"><thead><tr><th>Batch</th><th>Officer</th><th>Send Note</th><th>Status</th><th>Decision Note / Time</th></tr></thead><tbody>@foreach($voucher->currentApprovals->where('revision_no',$voucher->revision_no)->sortBy('approval_order') as $approval)<tr><td>#{{ $approval->batch_no ?: 1 }}</td><td>{{ $approval->approver?->name ?: $approval->approver_name ?: 'Former / unavailable user' }}<br><span class="small">{{ $approval->approver?->email ?: $approval->approver_email }}</span></td><td>{{ $approval->dispatch_note ?: '—' }}</td><td>{{ $approval->status }}</td><td>{{ $approval->comment ?: '—' }}<br><span class="small">{{ $approval->acted_at?->format('d M Y h:i A') ?: '—' }}</span></td></tr>@endforeach</tbody></table></div>
@if($voucher->sent_to_vendor_at)<p><strong>Sent to Vendor:</strong> {{ $voucher->sent_to_vendor_at->format('d M Y h:i A') }} by {{ $voucher->sentToVendorBy?->name ?: '—' }}</p>@endif
<p class="small muted">This document authorizes purchase up to the approved quantities and values shown above. Stock is increased only after actual supplier delivery is received in the Purchase module.</p>
</body></html>
